name: rush_cli
description: A new and improved way of building MIT AI2 extensions.
version: 2.0.0-rc01
homepage: https://github.com/shreyashsaitwal/rush-cli

executables:
  rush: rush.dart

environment:
  sdk: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.6
  build_version: ^2.1.1
  hive_generator: ^2.0.0
  json_serializable: ^6.7.1
  lints: ^2.0.1

dependencies:
  archive: ^3.3.7
  args: ^2.4.2
  checked_yaml: ^2.0.3
  collection: ^1.18.0
  crypto: ^3.0.3
  dart_console: ^1.2.0
  get_it: ^7.6.0
  github: ^9.17.0
  hive: ^2.2.3
  http: ^1.1.0
  interact: ^2.2.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  recase: ^4.1.0
  tint: ^2.1.0
  xml2json: ^6.2.0
  xrange: ^2.0.0

dependency_overrides:
  tint:
    git:
      url: https://github.com/shreyashsaitwal/tint
      ref: main
