name: rush_cli
description: A simple CLI to quickly scaffold App Inventor extensions.
version: 0.0.1+1
homepage: https://github.com/ShreyashSaitwal/rush-cli

executables:
  rush: rush.dart

authors:
  - Shreyash Saitwal

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0

publish_to: none

dependencies:
  archive: ^3.1.2
  args: ^2.0.0
  dart_console: ^1.0.0
  dio: ^4.0.0-beta5
  hive: ^2.0.0
  meta: ^1.3.0
  path: ^1.8.0
  yaml: ^3.1.0
  rush_prompt:
    path: ./packages/rush_prompt
