name: resolver
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  http: ^0.13.4
  path: ^1.8.0
  xml2json: ^5.3.2

dev_dependencies:
  lints: ^1.0.0
